### PR TITLE
replace nebulouslabs with skynethq

### PR DESCRIPTION
**Pull request by MSevey**

### CODE REVIEW

**Comment by dghelm** [comment]
Mostly good, but `skynet-js` isn't migrated yet, so we should wait to merge or just fix others and do another PR later

**Comment by mrcnski** [comment]
@MSevey You need to do the replacement in v3/index.html.md as well as that is the latest version, as well as v3-beta. v2 and v1 can remain as they are. Also I think you missed some links.

**Comment by MSevey** [comment]
> Mostly good, but `skynet-js` isn't migrated yet, so we should wait to merge or just fix others and do another PR later

skynet-js and now be migrated.

**Comment by MSevey** [comment]
> @MSevey You need to do the replacement in v3/index.html.md as well as that is the latest version, as well as v3-beta. v2 and v1 can remain as they are. Also I think you missed some links.

updated

What links do you think were missed? No other github references came up when I search through the index files.

**Comment by mrcnski** [comment]
Closing in flavor of https://github.com/SkynetHQ/skynet-docs/pull/12, which is more complete and handles the new v4 docs as well.

**Pull request closed without merging**
